### ISSUE TITLE
Help for installing sphinx-autoapi on ubuntu

### ISSUE THREAD

**Issue by xer0x** [rtfd/sphinx-autoapi#69]
Sorry if this is the wrong place. I'm trying to install sphinx-autoapi on ubuntu 14.04, and I'd like help.

I had to add the `--pre` flag to `pip install sphinx-autoapi`, but `sphinx-build` still says that `autoapi.extension` is missing.

Do I have the right names? Thanks for your help. 

Snippet of installation log:

```
$ pip install sphinx-autoapi --pre
...

$ python .../test/bin/sphinx-build -v -v -T -b readthedocs -d _build/doctrees-readthedocs -c /www/docs/ -D language=en . _build/html
Running Sphinx v1.3.5
[app] setting up extension: 'autoapi.extension'
Original exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 431, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
ImportError: No module named autoapi.extension


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension autoapi.extension (exception: No module named autoapi.extension)

Extension error:
Could not import extension autoapi.extension (exception: No module named autoapi.extension)
```

**Comment by agjohnson** [comment]
Hrm, yeah, names look okay. Looks like an import error. Are you able to `pyhon -mautoapi.extension` without an error message?

**Comment by xer0x** [comment]
I'll try..
