### ISSUE TITLE
NameError: name 'basestring' is not defined

### ISSUE THREAD

**Issue by danroth27** [rtfd/sphinx-autoapi#74]
```
# Sphinx version: 1.4.1
# Python version: 3.5.1 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\users\daroth\appdata\local\programs\python\python35\lib\site-packages\sphinx\cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "c:\users\daroth\appdata\local\programs\python\python35\lib\site-packages\sphinx\application.py", line 197, in __init__
    self._init_builder(self.buildername)
  File "c:\users\daroth\appdata\local\programs\python\python35\lib\site-packages\sphinx\application.py", line 269, in _init_builder
    self.emit('builder-inited')
  File "c:\users\daroth\appdata\local\programs\python\python35\lib\site-packages\sphinx\application.py", line 536, in emit
    results.append(callback(self, *args))
  File "c:\users\daroth\appdata\local\programs\python\python35\lib\site-packages\autoapi\extension.py", line 31, in run_autoapi
    if isinstance(autoapi_dirs, basestring):
NameError: name 'basestring' is not defined
```

**Comment by danroth27** [comment]
Looks like this is a Python 3 incompatibility
